// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC3CEuKQn3MSqPBpzRQKkK-T2cYMv9vXA',
    appId: '1:627196419317:web:487c2f037b3901db7579bc',
    messagingSenderId: '627196419317',
    projectId: 'delicia-e8974',
    authDomain: 'delicia-e8974.firebaseapp.com',
    storageBucket: 'delicia-e8974.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC3CEuKQn3MSqPBpzRQKkK-T2cYMv9vXA',
    appId: '1:627196419317:android:487c2f037b3901db7579bc',
    messagingSenderId: '627196419317',
    projectId: 'delicia-e8974',
    storageBucket: 'delicia-e8974.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC3CEuKQn3MSqPBpzRQKkK-T2cYMv9vXA',
    appId: '1:627196419317:ios:487c2f037b3901db7579bc',
    messagingSenderId: '627196419317',
    projectId: 'delicia-e8974',
    storageBucket: 'delicia-e8974.firebasestorage.app',
    iosBundleId: 'com.example.panaderiadeli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC3CEuKQn3MSqPBpzRQKkK-T2cYMv9vXA',
    appId: '1:627196419317:ios:487c2f037b3901db7579bc',
    messagingSenderId: '627196419317',
    projectId: 'delicia-e8974',
    storageBucket: 'delicia-e8974.firebasestorage.app',
    iosBundleId: 'com.example.panaderiadeli',
  );
}